### ISSUE TITLE
Error when assigning F2F task to user with F2F profile stats

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#168]
tonyj [10:22 PM]  
22:20:51,395 INFO  [STDOUT] Failed to get the user information for the userId 23,011,162
com.cronos.onlinereview.external.RetrievalException: Some parameters of RatingType.getRatingType() or RatingInfo.ctor() invalid.
    at com.cronos.onlinereview.external.impl.DBUserRetrieval.updateRatings(DBUserRetrieval.java:524)
    at com.cronos.onlinereview.external.impl.DBUserRetrieval.selectRating(DBUserRetrieval.java:655)
    at com.cronos.onlinereview.external.impl.DBUserRetrieval.retrieveUsers(DBUserRetrieval.java:383)
    at com.cronos.onlinereview.external.impl.DBUserRetrieval.retrieveUsers(DBUserRetrieval.java:237)
    at com.cronos.onlinereview.external.impl.DBUserRetrieval.retrieveUser(DBUserRetrieval.java:175)
    at com.cronos.onlinereview.services.uploads.impl.DefaultUploadServices.addSubmitter(DefaultUploadServices.java:1151)
    at com.cronos.onlinereview.services.uploads.impl.DefaultUploadExternalServices.addSubmitter(DefaultUploadExternalServices.java:517)
    at com.topcoder.service.facade.contest.ejb.ContestServiceFacadeBean.addSubmitter(ContestServiceFacadeBean.java:5152)
    at com.topcoder.service.facade.contest.ejb.ContestServiceFacadeBean.updatePreRegister(ContestServiceFacadeBean.java:4855)

**Comment by ajefts** [comment]
@skyhit I found more details about this error.  It's getting hit more often now.  This class (https://coder.topcoder.com/tcs/clients/cronos/components/user_project_data_store/trunk/src/java/main/com/cronos/onlinereview/external/RatingType.java) is checking for Rating Type.  However, there is no setting for F2F (I assume since it's not rated), so it's erroring when it tries to add the submitter.

Is it ok to add the constants for F2F and Code to this class?  Will that harm anything?

**Comment by skyhit** [comment]
@ajefts I think it is fine

**Comment by ajefts** [comment]
When you return, can you get that updated?

**Comment by skyhit** [comment]
@ajefts sure, mainly I think we should adjust the logic here - https://github.com/appirio-tech/direct-app/blob/master/services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java#L9134-L9174

**Comment by ajefts** [comment]
@skyhit What would change there?  Are you thinking of the other issue with the registration dates?
